In [1]:
import numpy as np

# Exercício 1

Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().

In [ ]:
a = np.array([
    [1,2,3],
    [2,1,-1]
])

b = np.array([
    [1,-2,0],
    [3,0,1],
    [4,5,6]
])

c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

d = np.array([[1,4,-3]]).reshape(-1,1)

print(a)
print()
print(b)
print()
print(c)
print()
print(d)

[[ 1  2  3]
 [ 2  1 -1]]

[[ 1 -2  0]
 [ 3  0  1]
 [ 4  5  6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1]
 [ 4]
 [-3]]


# Exercício 2

Defina as matrizes abaixo utilizando o NumPy. Use o método np.array()

In [ ]:
e = np.array(range(1,7)).reshape(-1,1)
f = np.array([1,0,3,-10])
g = np.array(range(1,6))

print(e)
print()
print(f)
print()
print(g)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

[  1   0   3 -10]

[1 2 3 4 5]


# Exercício 3

Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().

In [ ]:
a = np.zeros(shape = (2,2))
b = np.zeros(shape = (3,5))
c = np.ones(shape = (5,5))
i2 = np.eye(2)
i3 = np.eye(3)
i4 = np.eye(6)

print(a,'\n')
print(b,'\n')
print(c,'\n')
print(i2,'\n')
print(i3,'\n')
print(i4)

[[0. 0.]
 [0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[1. 0.]
 [0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Exercício 4

Defina a matrizes triangulares abaixo utilizando o NumPy. Use os métodos np.triu() e np.tril().

In [ ]:
a = np.triu(np.arange(1,10).reshape(3,3))
b = np.tril(np.arange(1,10).reshape(3,3))
c = np.triu(np.arange(100,125).reshape(5,5))

print(a,'\n')
print(b,'\n')
print(c)

[[1 2 3]
 [0 5 6]
 [0 0 9]] 

[[1 0 0]
 [4 5 0]
 [7 8 9]] 

[[100 101 102 103 104]
 [  0 106 107 108 109]
 [  0   0 112 113 114]
 [  0   0   0 118 119]
 [  0   0   0   0 124]]


# Exercício 5

Defina as matrizes abaixo utilizando o NumPy. Use os métodos np.diag() e np.array().

In [ ]:
a = np.diag([7,1,-1])
b = np.diag([3,3,3,3])
c = np.diag(range(-5,0))

print(a,'\n')
print(b,'\n')
print(c)

[[ 7  0  0]
 [ 0  1  0]
 [ 0  0 -1]] 

[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]] 

[[-5  0  0  0  0]
 [ 0 -4  0  0  0]
 [ 0  0 -3  0  0]
 [ 0  0  0 -2  0]
 [ 0  0  0  0 -1]]


# Operações Matriciais - Exercício 1

Defina as matrizes A e B dadas a seguir e obtenha A+B.

In [ ]:
a = np.array([
    [10,11],
    [5,1],
    [-2,4]
])

b = np.array([
    [1,25],
    [3,4],
    [0,-10]
])

print(a,'\n')
print(b,'\n')
print(f'A + B =\n{a+b}')

[[10 11]
 [ 5  1]
 [-2  4]] 

[[  1  25]
 [  3   4]
 [  0 -10]] 

A + B =
[[11 36]
 [ 8  5]
 [-2 -6]]


# Exercício 2

Para as matrizes a seguir,

Verifique as propriedades da adição de matrizes:
* a + b = b + a
* a + (b + c) = (a + b) + c
* a + 0 = a, em que 0 denota uma matriz nula de ordem m x n

In [ ]:
a = np.array([
    [10,11],
    [5,1],
    [-2,4]
])

b = np.array([
    [1,25],
    [3,4],
    [0,-10]
])

c = np.array([
    [7, 3],
    [6, 1],
    [0, 0]
])

matriz_nula = np.zeros(shape = (3,2))

print(a,'\n')
print(b,'\n')
print(c,'\n')

print(f'A + B =\n',a+b)
print()
print(f'B + A =\n',b+a)
print()
print(f'A + (B + C) =\n',a+(b+c))
print()
print(f'(A + B) + C =\n',(a+b)+c)
print()
print(f'A + 0 =\n',a+matriz_nula)

[[10 11]
 [ 5  1]
 [-2  4]] 

[[  1  25]
 [  3   4]
 [  0 -10]] 

[[7 3]
 [6 1]
 [0 0]] 

A + B =
 [[11 36]
 [ 8  5]
 [-2 -6]]

B + A =
 [[11 36]
 [ 8  5]
 [-2 -6]]

A + (B + C) =
 [[18 39]
 [14  6]
 [-2 -6]]

(A + B) + C =
 [[18 39]
 [14  6]
 [-2 -6]]

A + 0 =
 [[10. 11.]
 [ 5.  1.]
 [-2.  4.]]


# Exercício 3

Sejam as matrizes definidas a seguir, calculemos o que se pede na sequência.

a) a+b

b) a*c

c) b*c

d) c*d

e) d*a

f) d*b

g)-a

h)-d

i)2*a + 3*b

In [ ]:
a = np.array([
    [1,2,3],
    [2,1,-1],
])

b = np.array([
    [-2,0,1],
    [3,0,1]
])

c = np.array([-1,2,4]).reshape(-1,1)

d = np.array([[2,-1]])

print('A =\n',a)
print()
print('B =\n',b)
print()
print('C =\n',c)
print()
print('D =\n',d)
print()

# a)
print('a + b =\n{}'.format(a+b))

# b)
print('a * c =\n{}'.format(a.dot(c)))

# c)
print('b * c =\n{}'.format(b.dot(c)))

# d)
print('c * d =\n{}'.format(c.dot(d)))

# e)
print('d * a =\n{}'.format(d.dot(a)))

# f)
print('d * b =\n{}'.format(d.dot(b)))

# g)
print('-a =\n{}'.format(a*(-1)))

# h)
print('-d =\n{}'.format(d*(-1)))

# i)
print('2*a+3*b =\n{}'.format((a*2)+(3*b)))

A =
 [[ 1  2  3]
 [ 2  1 -1]]

B =
 [[-2  0  1]
 [ 3  0  1]]

C =
 [[-1]
 [ 2]
 [ 4]]

D =
 [[ 2 -1]]

a + b =
[[-1  2  4]
 [ 5  1  0]]
a * c =
[[15]
 [-4]]
b * c =
[[6]
 [1]]
c * d =
[[-2  1]
 [ 4 -2]
 [ 8 -4]]
d * a =
[[0 3 7]]
d * b =
[[-7  0  1]]
-a =
[[-1 -2 -3]
 [-2 -1  1]]
-d =
[[-2  1]]
2*a+3*b =
[[-4  4  9]
 [13  2  1]]


# Exercício 4

Sejam as matrizes A,B e C. Mostre que: AB = AC

In [ ]:
a = np.array([
    [1,-3,2],
    [2,1,-3],
    [4,-3,-1]
])

b = np.array([
    [1,4,1,0],
    [2,1,1,1],
    [1,-2,1,2]
])

c = np.array([
    [2,1,-1,-2],
    [3,-2,-1,-1],
    [2,-5,-1,0]
])

print('A:\n',a)
print()
print('B:\n',b)
print()
print('C:\n',c)
print()

print('A*B:\n',a.dot(b))
print()
print('A*C:\n',a.dot(c))

A:
 [[ 1 -3  2]
 [ 2  1 -3]
 [ 4 -3 -1]]

B:
 [[ 1  4  1  0]
 [ 2  1  1  1]
 [ 1 -2  1  2]]

C:
 [[ 2  1 -1 -2]
 [ 3 -2 -1 -1]
 [ 2 -5 -1  0]]

A*B:
 [[-3 -3  0  1]
 [ 1 15  0 -5]
 [-3 15  0 -5]]

A*C:
 [[-3 -3  0  1]
 [ 1 15  0 -5]
 [-3 15  0 -5]]


# Matriz Transposta - Exercício 1

Podemos obter a transposta de uma matriz permutando as linhas pelas colunas de mesmo índice(ou seja, o que é linha se transforma em coluna e o que é coluna se transforma em linha).

Obtenha a Matriz transposta das matrizes a seguir:

In [ ]:
a = np.array([
    [1,-3,2],
    [2,1,-3],
    [4,-3,-1]
])

b = np.array([
    [1,0,4],
    [-7,5,5],
    [25,9,11]
])

print('Matriz A:\n',a)
print()
print('Matriz B:\n',b)
print()

print('Matriz Transposta de A:\n',a.T)
print()
print('Matriz Transposta de B:\n',b.T)

Matriz A:
 [[ 1 -3  2]
 [ 2  1 -3]
 [ 4 -3 -1]]

Matriz B:
 [[ 1  0  4]
 [-7  5  5]
 [25  9 11]]

Matriz Transposta de A:
 [[ 1  2  4]
 [-3  1 -3]
 [ 2 -3 -1]]

Matriz Transposta de B:
 [[ 1 -7 25]
 [ 0  5  9]
 [ 4  5 11]]


# Determinante - Exercício 1

Obtenha o determinante das matrizes a seguir. Utilize o método np.linalg.det().

In [ ]:
a = np.array([[5]])
b = np.array([
    [1,2],
    [3,4]
    ])
c = np.array([
    [-3,-8],
    [-5,-2]
])
d = np.eye(2)

print('Matriz A:\n',a)
print()
print('Matriz B:\n',b)
print()
print('Matriz C:\n',c)
print()
print('Matriz D:\n',d)
print()

print('Determinante de A:\n',np.linalg.det(a))
print()
print('Determinante de B:\n',np.linalg.det(b))
print()
print('Determinante de C:\n',np.linalg.det(c))
print()
print('Determinante de D:\n',np.linalg.det(d))

Matriz A:
 [[5]]

Matriz B:
 [[1 2]
 [3 4]]

Matriz C:
 [[-3 -8]
 [-5 -2]]

Matriz D:
 [[1. 0.]
 [0. 1.]]

Determinante de A:
 4.999999999999999

Determinante de B:
 -2.0000000000000004

Determinante de C:
 -34.00000000000001

Determinante de D:
 1.0


# Exercício 2

Obtenha o determinante das matrizes a seguir. Utilize o método np.linalg.det().

In [ ]:
a = np.array([
    [3, 1, 4],
    [10, 7, 5],
    [1, 4, 4]
])

b = np.eye(3)

c = np.diag([5,10,2])

d = np.diag([3,7,11,2])

e = np.array([
    [5,0,13,12],
    [1,-1,25,7],
    [6,2,1,20],
    [11,4,0,-9]
])

print('Matriz A:\n',a)
print()
print('Matriz B:\n',b)
print()
print('Matriz C:\n',c)
print()
print('Matriz D:\n',d)
print()
print('Matriz E:\n',e)
print()

print('Determinante de A:\n',np.linalg.det(a))
print()
print('Determinante de B:\n',np.linalg.det(b))
print()
print('Determinante de C:\n',np.linalg.det(c))
print()
print('Determinante de D:\n',np.linalg.det(d))
print()
print('Determinante de E:\n',np.linalg.det(e))

Matriz A:
 [[ 3  1  4]
 [10  7  5]
 [ 1  4  4]]

Matriz B:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz C:
 [[ 5  0  0]
 [ 0 10  0]
 [ 0  0  2]]

Matriz D:
 [[ 3  0  0  0]
 [ 0  7  0  0]
 [ 0  0 11  0]
 [ 0  0  0  2]]

Matriz E:
 [[ 5  0 13 12]
 [ 1 -1 25  7]
 [ 6  2  1 20]
 [11  4  0 -9]]

Determinante de A:
 121.00000000000003

Determinante de B:
 1.0

Determinante de C:
 100.00000000000004

Determinante de D:
 461.9999999999999

Determinante de E:
 7080.999999999999


# Exercício 3

Dada as matrizes A e B, calcule:

a) detA + detB

b) det(a+b)

In [ ]:
a = np.array([[1,2],[1,0]])
b = np.array([[3,-1],[0,1]])

print('Matriz A:\n',a)
print()
print('Matriz B:\n',b)
print()

# a)
print('detA + detB =\n',(np.linalg.det(a))+(np.linalg.det(b)))
print()

# b)
soma = a+b
print('det(A + B) =\n',np.linalg.det(soma))

Matriz A:
 [[1 2]
 [1 0]]

Matriz B:
 [[ 3 -1]
 [ 0  1]]

detA + detB =
 1.0000000000000004

det(A + B) =
 2.9999999999999996


# Matriz Inversa - Exercício 1

Encontre a inversa das matrizes abaixo. Use o método np.linalg.inv().

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[-1,3],[5,4]])

print('Matriz A:\n',a)
print()
print('Matriz B:\n',b)
print()

print('Matriz inversa de A =\n',np.linalg.inv(a))
print()
print('Matriz Inversa de B =\n',np.linalg.inv(b))

Matriz A:
 [[1 2]
 [3 4]]

Matriz B:
 [[-1  3]
 [ 5  4]]

Matriz inversa de A =
 [[-2.   1. ]
 [ 1.5 -0.5]]

Matriz Inversa de B =
 [[-0.21052632  0.15789474]
 [ 0.26315789  0.05263158]]


# Exercício 2

Encontre a inversa da matriz A

In [ ]:
a = np.array([
    [4,-1,2,-2],
    [3,-1,0,0],
    [2,3,1,0],
    [0,7,1,1]
])

print('Matriz A:\n',a)
print()
print('Matriz inversa de A =\n',np.linalg.inv(a))

Matriz A:
 [[ 4 -1  2 -2]
 [ 3 -1  0  0]
 [ 2  3  1  0]
 [ 0  7  1  1]]

Matriz inversa de A =
 [[ -1.  -1.   4.  -2.]
 [ -3.  -4.  12.  -6.]
 [ 11.  14. -43.  22.]
 [ 10.  14. -41.  21.]]


# Exercício 3

Encontre a inversa da matriz A.

In [ ]:
a = np.diag([7,8,11,2,4,5,1,3])

print('Matriz A:')
print(a,'\n')

inversa = np.linalg.inv(a)
print('Inversa da matriz A:')
print(inversa)

Matriz A:
[[ 7  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0]
 [ 0  0  0  2  0  0  0  0]
 [ 0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  5  0  0]
 [ 0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  3]] 

Inversa da matriz A:
[[0.14285714 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.125      0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.09090909 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.5        0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.25       0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.2
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.33333333]]


# Sistemas Lineares - Exercício 1

Resolva os sistemas lineares a seguir. Utilize o método np.linalg.solve().

2x + 3y = 6

x - y = 8

In [ ]:
a = np.array([[2,3],[1,-1]])
b = np.array([[6],[8]])

resposta = np.linalg.solve(a,b)
for i in range(0,2):
  if i == 0:
    print(f'x = {resposta[i]}')
  else:
    print(f'y = {resposta[i]}')

x = [6.]
y = [-2.]


# Exercício 2

Resolva o sistema linear abaixo.

x + 3z = -8

2x - 4y = -4

3x - 2y - 5z = 26

In [ ]:
a = np.array([[1,0,3],[2,-4,0],[3,-2,-5]])
b = np.array([[-8],[-4],[26]])

resposta = np.linalg.solve(a,b)
for i in range(0,3):
  if i == 0:
    print(f'x = {resposta[i]}')
  elif i == 1:
    print(f'y = {resposta[i]}')
  else:
    print(f'z = {resposta[i]}')

x = [4.]
y = [3.]
z = [-4.]


# Exercício 3

Resolva o sistema linear abaixo. Utilize o método np.linalg.solve().

x + y + z + w = 0

x + y + z - w = 4

x + y - z + w = -4

x - y + z + w = 2

In [ ]:
a = np.array([[1,1,1,1],[1,1,1,-1],[1,1,-1,1],[1,-1,1,1]])
b = np.array([[0],[4],[-4],[2]])

resposta = np.linalg.solve(a,b)
for i in range(0,4):
  if i == 0:
    print(f'x = {resposta[i]}')
  elif i == 1:
    print(f'y = {resposta[i]}')
  elif i == 2:
    print(f'z = {resposta[i]}')
  else:
    print(f'w = {resposta[i]}')

x = [1.]
y = [-1.]
z = [2.]
w = [-2.]


# Exercício 4

Resolva o sistema linear abaixo.

3x + 2y = 2

x - y = 4

5y + z = -1

In [ ]:
a = np.array([[3,2,0],[1,-1,0],[0,5,1]])
b = np.array([[2],[4],[-1]])


resposta = np.linalg.solve(a,b)
for i in range(0,3):
  if i == 0:
    print(f'x = {resposta[i]}')
  elif i == 1:
    print(f'y = {resposta[i]}')
  else:
    print(f'z = {resposta[i]}')

x = [2.]
y = [-2.]
z = [9.]


# Traço de uma Matriz - Exercício 1

Obtenha o traço das matrizes abaixo:

Lembrete: o traço de uma matriz é definido como a soma dos elementos da sua diagonal principal. Desta forma, facilmente podemos dizer que o traço da matriz A é 5, da matriz B 16 e da matriz C 2. Use o método matrix.trace().

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array(([10,0,11],[-7,2,5],[45,78,4]))
c = np.array(([4,2,11,14],[0,-9,1,3],[-3,4,5,8],[0,1,1,2]))

print('Matriz A:')
print(a)
print()
print('Matriz B:')
print(b)
print()
print('Matriz C:')
print(c)
print()

print(f'Traço matriz A = {a.trace()}')
print(f'Traço matriz B = {b.trace()}')
print(f'Traço matriz C = {c.trace()}')

Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[10  0 11]
 [-7  2  5]
 [45 78  4]]

Matriz C:
[[ 4  2 11 14]
 [ 0 -9  1  3]
 [-3  4  5  8]
 [ 0  1  1  2]]

Traço matriz A = 5
Traço matriz B = 16
Traço matriz C = 2


# Posto matricial - Exercício 1

Obtenha o posto (ou rank) da matriz K. Use o método np.linalg.matrix_rank().

Lembrete: posto é o número de linhas não nulas da matriz quando escrita em sua forma escalonada por linhas.

In [4]:
k = np.array([[2,-1,3],[1,4,2],[1,-5,1],[4,16,8]])

print('Matriz K:')
print(k,'\n')

posto = np.linalg.matrix_rank(k)
print('Posto da matriz K = {}'.format(posto))

Matriz K:
[[ 2 -1  3]
 [ 1  4  2]
 [ 1 -5  1]
 [ 4 16  8]] 

Posto da matriz K = 2


# Autovalor/Autovetor - Exercício 1

Calcule os autovalores associadoas a matriz A. Utilize o método np.linalg.eigvals().


In [5]:
a = np.array([[1,3],[-1,5]])

print('Matriz A:')
print(a,'\n')

autovalor = np.linalg.eigvals(a)
print('Autovalores da matriz A = {}'.format(autovalor))

Matriz A:
[[ 1  3]
 [-1  5]] 

Autovalores da matriz A = [2. 4.]
