# Importando a biblioteca Numpy


In [ ]:
import numpy as np

# Exercício 1

Crie um array  e inspecione os seguintes atributos:

* shape: uma tupla que contém o número de elementos (tamanho) em cada dimensão do array;
* size: número total de elementos do array;
* ndim: número de dimensões (eixos);
* nbytes: número de bytes utilizado no armazenamento dos dados;
* dtype: data type dos elementos do array.

In [ ]:
vetor1 = np.array([1, 2, 3, 4, 5])

In [ ]:
print('O vetor criado é',vetor1)

O vetor criado é [1 2 3 4 5]


In [ ]:
print('Shape =',vetor1.shape)

Shape = (5,)


In [ ]:
print('Size =',vetor1.size)

Size = 5


In [ ]:
print('Número de dimensões =',vetor1.ndim)

Número de dimensões = 1


In [ ]:
print('Número de bytes =',vetor1.nbytes)

Número de bytes = 40


In [ ]:
print('O tipo de dados presentes no vetor =',vetor1.dtype)

O tipo de dados presentes no vetor = int64


# Exercício 2

Com base no exercício anterior crie uma função que receba um array e mostre na tela seus atributos. Verifique se o argumento inserido é de fato um objeto numpy. Use também a função built-in type() para verificar a classe do objeto.

In [ ]:
def inspecionar_array(a):
  global b
  if type(a) == b:
    print('Shape:',a.shape)
    print('Size:',a.size)
    print('Número de dimensões:',a.ndim)
    print('Tipo dos dados:',a.dtype)
    print('Classe:',type(a))
    print(a)
  else:
    print('O objeto inserido não é array Numpy')

vetor2 = np.array([1, 2, 3])
b = type(vetor2)
inspecionar_array(vetor1)

Shape: (5,)
Size: 5
Número de dimensões: 1
Tipo dos dados: int64
Classe: <class 'numpy.ndarray'>
[1 2 3 4 5]


# Exercício 3
Use a função np.array() para criar os arrays unidimensionais listados abaixo:

a) Use uma lista como argumento e obtenha: array([-1,  4,  7,  9])

b) Use a função range() e obtenha: array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

c) Use uma tupla como argumento e obtenha: array([10, 11, 12, 13, 14])

d) Use a função range() e obtenha: array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

e) Use a função range() e obtenha: array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920, 1910, 1900])

f) Obtenha: array(100)

In [ ]:
# a)
lista = [-1, 4, 7, 9]
vetor_a = np.array(lista)
vetor_a

array([-1,  4,  7,  9])

In [ ]:
# b)
vetor_b = np.array(range(1,11))
vetor_b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# c)
tupla = tuple(range(10,15))
vetor_c = np.array(tupla)
vetor_c

array([10, 11, 12, 13, 14])

In [ ]:
# d)
vetor_d = np.arange(1990,2025,5)
vetor_d

array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

In [ ]:
# e)
vetor_e = np.arange(2020,1890,-10)
vetor_e

array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])

In [ ]:
# f)
vetor_f = np.array([100])
vetor_f

array([100])

# Exercício 4
A função np.ones() permite criar um array preenchido com o número 1 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array. Use esta função para criar os arrays a seguir:

a) array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

b) array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

c) array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
def configuracao_array_1 (dado,*tamanho):
    i = 0
    if len(tamanho) == 1:
      vetor_4 = np.ones((tamanho))
    else:
      for dimensoes in tamanho:
        if i == 0:
          linha = dimensoes
        else:
          coluna = dimensoes
        i+=1
      vetor_4 = np.ones((linha, coluna))
      if dado == 'flutuante':
        vetor_4 = vetor_4.astype(float)
      else:
        vetor_4 = vetor_4.astype(int)

    return vetor_4


print('Criando vetor ou matriz apenas com o número 1:\n')
linhas_colunas = []
teste_respostas = False
while teste_respostas == False:
  teste_opcao = False
  while teste_opcao == False:
    opcao = input('Deseja criar um vetor de quantas linhas? ')
    if opcao == '1':
      teste_opcao = True
      qtd = int(input('Digite a quantidade de números que teremos no vetor: '))
      linhas_colunas.append(qtd)
    else:
      teste_opcao = True
      opcao = int(opcao)
      linhas_colunas.append(opcao)
      colunas = int(input('Digite um número para a quantidade de colunas do vetor: '))
      linhas_colunas.append(colunas)
  teste_dados = False
  while teste_dados == False:
    dados = input('Qual o tipo de dados do vetor: inteiro ou flutuante? ')
    if dados == 'flutuante':
      teste_dados = True
    elif dados == 'inteiro':
      teste_dados = True
    else:
      print('Tipo de dados inválido.')
  teste_respostas = True

print()
configuracao_array_1(dados,*linhas_colunas)

Criando vetor ou matriz apenas com o número 1:

Deseja criar um vetor de quantas linhas? 1
Digite a quantidade de números que teremos no vetor: 20
Qual o tipo de dados do vetor: inteiro ou flutuante? nfoe
Tipo de dados inválido.
Qual o tipo de dados do vetor: inteiro ou flutuante? 13165
Tipo de dados inválido.
Qual o tipo de dados do vetor: inteiro ou flutuante? inteiro



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

# Exercício 5

A função np.zeros() permite criar um array preenchido com o número 0 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array (default é o float). Use esta função para criar os arrays a seguir:

a) array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

b) array([[0., 0.],
       [0., 0.]])

c) array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
def configuracao_array_0 (dado,*tamanho):
    i = 0
    if len(tamanho) == 1:
      vetor_5 = np.zeros((tamanho))
    else:
      for dimensoes in tamanho:
        if i == 0:
          linha = dimensoes
        else:
          coluna = dimensoes
        i+=1
      vetor_5 = np.zeros((linha, coluna))
      if dado == 'flutuante':
        vetor_5 = vetor_5.astype(float)
      else:
        vetor_5 = vetor_5.astype(int)

    return vetor_5


print('Criando vetor ou matriz apenas com o número 0:\n')
linhas_colunas = []
teste_respostas = False
while teste_respostas == False:
  teste_opcao = False
  while teste_opcao == False:
    opcao = input('Deseja criar um vetor de quantas linhas? ')
    if opcao == '1':
      teste_opcao = True
      qtd = int(input('Digite a quantidade de números que teremos no vetor: '))
      linhas_colunas.append(qtd)
    else:
      teste_opcao = True
      opcao = int(opcao)
      linhas_colunas.append(opcao)
      colunas = int(input('Digite um número para a quantidade de colunas do vetor: '))
      linhas_colunas.append(colunas)
  teste_dados = False
  while teste_dados == False:
    dados = input('Qual o tipo de dados do vetor: inteiro ou flutuante? ')
    if dados == 'flutuante':
      teste_dados = True
    elif dados == 'inteiro':
      teste_dados = True
    else:
      print('Tipo de dados inválido.')
  teste_respostas = True

print()
configuracao_array_0(dados,*linhas_colunas)

Criando vetor ou matriz apenas com o número 0:

Deseja criar um vetor de quantas linhas? 6
Digite um número para a quantidade de colunas do vetor: 1
Qual o tipo de dados do vetor: inteiro ou flutuante? flutuante



array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

# Exercício 6
Crie os arrays a seguir:

a)
array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]]) -> vetor coluna

b) array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])

c) array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]]) -> matriz 5x10

In [ ]:
# a)
vetor_6 = np.arange(10,50,5).reshape(-1,1)
vetor_6

array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])

In [ ]:
# b)
vetor_6b = np.arange(-50,0,5)
vetor_6b

array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])

In [ ]:
# c)
matrix_6c = np.array(range(50,150,2)).reshape(5,10)
matrix_6c

array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])

# Exercício 7

Utilize a função np.full(shape, fill_value, dtype) para criar os arrays a seguir. Esta função permite criar um array com um shape e dtype definidos pelo usuário, preenchido com um determinado valor.

a) array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

b) array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

c) array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

d) array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]]) -> matriz quadrada 10x10

In [ ]:
def configuracao_array (dado,valor,*tamanho):
  if dado == 'flutuante':
    if len(tamanho) == 1:
      vetor_7 = np.full((tamanho), valor, dtype=float)
    else:
      i = 0
      for dimensoes in tamanho:
        if i == 0:
          linha = dimensoes
        else:
          coluna = dimensoes
        i+=1
      vetor_7 = np.full((linha, coluna), valor, dtype = float)
  else:
    if len(tamanho) == 1:
      vetor_7 = np.full((tamanho), valor, dtype = int)
    else:
      i = 0
      for dimensoes in tamanho:
        if i == 0:
          linha = dimensoes
        else:
          coluna = dimensoes
        i+=1
      vetor_7 = np.full((linha, coluna), valor, dtype = int)

  return vetor_7


print('Criando vetor ou matriz:\n')
linhas_colunas = []
num = 0
dados = ''
teste_respostas = False
while teste_respostas == False:
  teste_num = False
  while teste_num == False:
    num = input('Digite um número para preencher o vetor ou matriz: ')
    try:
      num_int = int(num)
      teste_num = True
    except ValueError:
      print('Somente números inteiros são aceitos.')

  teste_opcao = False
  while teste_opcao == False:
    opcao = input('Deseja criar um vetor de quantas linhas? ')
    try:
      opcao_int = int(opcao)
      if opcao_int == 1:
        teste_opcao = True
        qtd = int(input('Digite a quantidade de números que teremos no vetor: '))
        linhas_colunas.append(qtd)
      elif opcao_int > 1:
        teste_opcao = True
        linhas_colunas.append(opcao_int)
        colunas = int(input('Digite um número para a quantidade de colunas do vetor: '))
        linhas_colunas.append(colunas)
      else:
        print('Digite um número inteiro maior ou igual a 1.')
    except ValueError:
      print('Somente números inteiros são aceitos.')

  teste_dados = False
  while teste_dados == False:
    dados = input('Qual o tipo de dados do vetor: inteiro ou flutuante? ')
    if dados == 'flutuante':
      teste_dados = True
    elif dados == 'inteiro':
      teste_dados = True
    else:
      print('Tipo de dados inválido.')

  teste_respostas = True

print()
configuracao_array(dados,num_int,*linhas_colunas)

Criando vetor ou matriz:

Digite um número para preencher o vetor ou matriz: 50
Deseja criar um vetor de quantas linhas? 10
Digite um número para a quantidade de colunas do vetor: 10
Qual o tipo de dados do vetor: inteiro ou flutuante? inteiro



array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

# Exercício 8

Defina o array K e verifique se há dados ausentes (missing data). Use a função np.isnan().

In [ ]:
K = np.array([
  [np.nan, 1, 10, 0],
  [np.nan, np.nan, np.nan, np.nan],
  [100, 50, np.nan, -25],
  [30, np.nan, np.nan, 130]
              ])

nulo = np.isnan(K)
print(f'Na matriz:\n{K}\ntemos {nulo.sum()} valores nulos.'
)

Na matriz:
[[ nan   1.  10.   0.]
 [ nan  nan  nan  nan]
 [100.  50.  nan -25.]
 [ 30.  nan  nan 130.]]
temos 8 valores nulos.


# Exercício 9

A função np.linspace() retorna um array com números contendo espaçamento uniforme em um intervalo definido. Crie um array com números dentro do intervalo [1,21] em 5 partes.

In [ ]:
array_9 = np.linspace(1,21,5)
array_9

array([ 1.,  6., 11., 16., 21.])

# Exercício 10

A função np.logspace() retorna números com espaçamento uniforme em uma escala logarítmica. Crie um array com números dentro do intervalo [1, 51] em 10 partes com a função np.logspace().

In [ ]:
array_10 = np.logspace(1,51,10).reshape(-1,1)
array_10

array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])

# Exercício 11

Use a função np.diag() para construir o array a seguir:

array([

  [ 5,  0,  0,  0,  0,  0],

  [ 0, 10,  0,  0,  0,  0],

  [ 0,  0, 15,  0,  0,  0],

  [ 0,  0,  0, 20,  0,  0],

  [ 0,  0,  0,  0, 25,  0],

  [ 0,  0,  0,  0,  0, 30]
  
  ])

In [ ]:
array_11 = np.diag([5, 10, 15, 20, 25, 30]).reshape(6,6)
array_11

array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])

# Exercício 12

Use a função np.eye() (ou ainda np.identity()) para obter o array seguir.

array([
      
      [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
      [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
      [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
      [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
      [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
      [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
      [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
      [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
      [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


In [ ]:
array_12 = np.eye(10)
array_12

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Exercício 14

Obtenha a soma dos elementos de cada array a seguir. Use a função np.sum(). Implemente uma solução com loop for, para tanto armazene os vetores em uma lista.

array1 = np.arange(1,11)

array2 = np.linspace(1,50,10)

array3 = np.array(range(51))

array4 = np.logspace(1,10,5)

array5 = np.diag(range(5,31,5))

In [ ]:
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

lista_soma = []
for i in range(0,5):
  if i == 0:
    lista_soma.append(array1.sum())
    print(f'Soma dos elementos do array 1: {lista_soma[i]}')
  elif i == 1:
    lista_soma.append(array2.sum())
    print(f'Soma dos elementos do array 2: {lista_soma[i]}')
  elif i == 2:
    lista_soma.append(array3.sum())
    print(f'Soma dos elementos do array 3: {lista_soma[i]}')
  elif i == 3:
    lista_soma.append(array4.sum())
    print(f'Soma dos elementos do array 4: {lista_soma[i]}')
  else:
    lista_soma.append(array5.sum())
    print(f'Soma dos elementos do array 5: {lista_soma[i]}')

Soma dos elementos do array 1: 55
Soma dos elementos do array 2: 255.0
Soma dos elementos do array 3: 1275
Soma dos elementos do array 4: 10056552148.564463
Soma dos elementos do array 5: 105


# Exercício 15

A partir da matriz definida abaixo obtenha:

a) soma total dos elementos;

b) soma das linhas ;

c) soma das colunas.

matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)

In [ ]:
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)
print(matriz,'\n')

# a)
soma_total = matriz.sum()
print(f'A soma de todos os elementos da matriz acima é {soma_total}\n')

# b)
for i in range(0,5):
  soma_linha = 0
  for j in range(0,3):
    soma_linha += matriz[i][j]
  print(f'A soma da linha {i+1} é {soma_linha}')

print()
# c)
for i in range(0,3):
  soma_coluna = 0
  for j in range(0,5):
    soma_coluna += matriz[j][i]
  print(f'A soma da coluna {i+1} é {soma_coluna}')

# Outra forma de fazer soma de linhas e colunas de matrizes:
# Soma_das_linhas = matriz.sum(axis = 1)
# print(Soma_das_linhas)

# Soma_das_colunas = matriz.sum(axis = 0)
# print(Soma_das_colunas)

[[49 55 73]
 [52 45 33]
 [58  1 34]
 [89 62 30]
 [24 64 63]] 

A soma de todos os elementos da matriz acima é 732

A soma da linha 1 é 177
A soma da linha 2 é 130
A soma da linha 3 é 93
A soma da linha 4 é 181
A soma da linha 5 é 151

A soma da coluna 1 é 272
A soma da coluna 2 é 227
A soma da coluna 3 é 233


# Exercício 16

Obtenha o valor máximo e o valor mínimo de cada array abaixo. Implemente uma solução com loop for.

array1 = np.array([-1, 10, 3, 4, 7, 27])

array2 = np.random.randint(-100,300,30)

array3 = np.random.randn(10)

array4 = np.array(range(50,10,-2))

In [ ]:
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))
arrays = [array1, array2, array3, array4]

for i, array in enumerate(arrays, start = 1):
  print(f'O valor máximo do array {i} é {array.max()}')
  print(f'O valor mínimo do array {i} é {array.min()}')
  print()

O valor máximo do array 1 é 27
O valor mínimo do array 1 é -1

O valor máximo do array 2 é 297
O valor mínimo do array 2 é -84

O valor máximo do array 3 é 1.9590115104071466
O valor mínimo do array 3 é -1.3072150803137645

O valor máximo do array 4 é 50
O valor mínimo do array 4 é 12



# Exercício 17

Crie uma função que receba uma matriz como entrada e calcule:

a) Valor máximo da matriz;

b) Valor máximo por coluna;

c) Valor máximo por linha;

d) Valor mínimo da matriz;

e) Valor mínimo por coluna;

f) Valor mínimo por linha.

In [ ]:
def inspecionar_matriz(matriz):
  print('Matriz:\n',matriz,'\n')
  print('-'*10,'Máximos','-'*10,'\n')
  print('Valor máximo da matriz: {}\n'.format(matriz.max()))

  for i in range(0,3):
    print(f'Valor máximo da linha {i+1} é {matriz[i].max()}')

  print()
  coluna = []
  for i in range(0,2):
    for j in range(0,3):
      coluna.append(matriz[j][i])
    maior_valor = coluna[0]
    for n in coluna:
      if n > maior_valor:
        maior_valor = n
    print(f'Valor máximo da coluna {i+1} é {maior_valor}')
    coluna.clear()

  print()
  print('-'*10,'Mínimos','-'*10,'\n')
  print('Valor mínimo da matriz: {}\n'.format(matriz.min()))

  for i in range(0,3):
    print(f'Valor mínimo da linha {i+1} é {matriz[i].min()}')

  print()
  for i in range(0,2):
    for j in range(0,3):
      coluna.append(matriz[j][i])
    menor_valor = coluna[0]
    for n in coluna:
      if n < menor_valor:
        menor_valor = n
    print(f'Valor mínimo da coluna {i+1} é {menor_valor}')
    coluna.clear()



array_17 = np.random.randint(1,10,6).reshape(3,2)
inspecionar_matriz(array_17)

Matriz:
 [[9 4]
 [6 8]
 [6 2]] 

---------- Máximos ---------- 

Valor máximo da matriz: 9

Valor máximo da linha 1 é 9
Valor máximo da linha 2 é 8
Valor máximo da linha 3 é 6

Valor máximo da coluna 1 é 9
Valor máximo da coluna 2 é 8

---------- Mínimos ---------- 

Valor mínimo da matriz: 2

Valor mínimo da linha 1 é 4
Valor mínimo da linha 2 é 6
Valor mínimo da linha 3 é 2

Valor mínimo da coluna 1 é 6
Valor mínimo da coluna 2 é 2


# Exercício 18

Com base no array definido abaixo obtenha sua média, mediana, variância e desvio padrão.

arr = np.random.normal(40,0.5,size = (300))

In [ ]:
arr = np.random.normal(40,0.5,size = 300)

media = np.mean(arr)
mediana = np.median(arr)
desvio_padrao = np.std(arr)
variancia = np.var(arr)

print(f'Media = {media}')
print(f'Mediana = {mediana}')
print(f'Desvio Padrão = {desvio_padrao}')
print(f'Variância = {variancia}')

Media = 40.01176753480569
Mediana = 39.99791603733746
Desvio Padrão = 0.49914091702190694
Variância = 0.2491416550454702


# Exercício 19

Com base nos arrays definidos a seguir obtenha a matriz de covariância e a matriz de correlação.

x = np.random.rand(100)
y = np.random.uniform(size=100)

In [ ]:
x = np.random.rand(100)
y = np.random.uniform(size=100)

print(f'Matriz de correlação:\n{np.corrcoef(x, y)}')
print()
print(f'Matriz de covariância:\n{np.cov(x, y)}')

Matriz de correlação:
[[1.         0.01695562]
 [0.01695562 1.        ]]

Matriz de covariância:
[[0.08103127 0.00150215]
 [0.00150215 0.09686077]]


# Exercício 20

Obtenha o índice do valor máximo do array A.
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])

In [ ]:
A = np.array([
    [11,15,33,105],
    [1,140,45,90],
    [67,230,78,99]])

print(A,'\n')
print(f'O valor máximo da matriz A é {A.max()}')
print(f'O índice do valor máximo da matriz A é {np.argmax(A)}')

[[ 11  15  33 105]
 [  1 140  45  90]
 [ 67 230  78  99]] 

O valor máximo da matriz A é 230
O índice do valor máximo da matriz A é 9


# Exercício 21

Obtenha o índice do valor mínimo do array B.

B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])


In [ ]:
B = np.array([
    [73, 22, 20, 62, 3],
    [68, 84, 27, 59, 93],
    [48, 52, 4, 55, 50],
    [42, 23, 63, 67, 4],
    [44, 30, 41, 31, 29]])

print(B,'\n')
print(f'O valor mínimo da matriz B é {B.min()}')
print(f'O índice do valor mínimo da matriz B é {np.argmin(B)}')

[[73 22 20 62  3]
 [68 84 27 59 93]
 [48 52  4 55 50]
 [42 23 63 67  4]
 [44 30 41 31 29]] 

O valor mínimo da matriz B é 3
O índice do valor mínimo da matriz B é 4


# Exercício 22

Escreva uma função que receba um array NumPy e mostre na tela um conjunto de  estatísticas descritivas deste objeto (valor máximo, valor mínimo, média, mediana, variância, desvio padrão).

In [ ]:
def info_array(array):
  print('-'*5,'Estatística Descritiva','-'*5,'\n')
  print(f'Valor máximo: {array.max()}')
  print(f'Valor mínimo: {array.min()}')
  print(f'Média: {np.mean(array)}')
  print(f'Mediana: {np.median(array)}')
  print(f'Variância: {np.var(array)}')
  print(f'Desvio padrão: {np.std(array)}')


teste_array = False
while teste_array == False:

  teste_linhas = False
  while teste_linhas == False:
    linhas = input('Quantas linhas terá o seu vetor/matriz? ')
    try:
      linhas_int = int(linhas)
      if linhas_int > 0:
        teste_linhas = True
      else:
        print('Digite um número inteiro maior que 0.')
    except ValueError:
      print('Digite um número inteiro maior que 0.')
  print()

  teste_colunas = False
  while teste_colunas == False:
    colunas = input('Quantas colunas terá o seu vetor/matriz? ')
    try:
      colunas_int = int(colunas)
      if colunas_int > 0:
        teste_colunas = True
      else:
        print('Digite um número inteiro maior que 0.')
    except ValueError:
      print('Digite um número inteiro maior que 0.')

  print()
  lista_numeros = []
  for i in range(0,linhas_int):
    for j in range(0,colunas_int):
      teste_numero = False
      while teste_numero == False:
        numero = input(f'Digite um número para a posição {j+1} da linha {i+1}: ')
        try:
          numero_float = float(numero)
          lista_numeros.append(numero_float)
          teste_numero = True
        except ValueError:
          print('Somente números são aceitos.')

  teste_array = True

matriz = np.array(lista_numeros).reshape(linhas_int, colunas_int)
print('\nVetor/Matriz formado:\n',matriz,'\n')
info_array(matriz)

Quantas linhas terá o seu vetor/matriz? 1

Quantas colunas terá o seu vetor/matriz? 5

Digite um número para a posição 1 da linha 1: 10
Digite um número para a posição 2 da linha 1: 20
Digite um número para a posição 3 da linha 1: 30
Digite um número para a posição 4 da linha 1: 40
Digite um número para a posição 5 da linha 1: 50

Vetor/Matriz formado:
 [[10. 20. 30. 40. 50.]] 

----- Estatística Descritiva ----- 

Valor máximo: 50.0
Valor mínimo: 10.0
Média: 30.0
Mediana: 30.0
Variância: 200.0
Desvio padrão: 14.142135623730951


# Exercício 23

Use a função np.unique() para obter um array com os elementos únicos do array abaixo. Para tanto, armazene o novo array em uma variável.



A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])

In [ ]:
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]
])

B = np.unique(A)
print(B)

[ 1  3  4  5  7 11]


# Exercício 24

Considerando os arrays abaixo:

array1 = np.array([10, 20, 30, 40])

array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])

Obtenha:

a) o primeiro, o terceiro e o último elemento de cada array;

b) inverta o array;

c) pegue o número 20 em ambos os arrays e armazene a soma em uma variável.

In [ ]:
array1 = np.array([10,20,30,40])
array2 = np.array([100,30,5,1,40,100,20,130,155,170])
print('Vetor1 = ',array1,'\n')
print('Vetor2 = ',array2,'\n')

# a)
print(f'Primeiro elemento vetor1: {array1[0]}')
print(f'Primeiro elemento vetor2: {array2[0]}')
print(f'Terceiro elemento vetor1: {array1[2]}')
print(f'Terceiro elemento vetor2: {array2[2]}')
print(f'Último elemento vetor1: {array1[-1]}')
print(f'Último elemento vetor2: {array2[-1]}')

print()
#b)
print(f'Vetor1 invertido = {array1[::-1]}')
print(f'Vetor2 invertido = {array2[::-1]}')

#c)
ind1 = 0
i = 0
for numero in array1:
  if numero == 20:
    ind1 = i
  i += 1

ind2 = 0
j = 0
for numero in array2:
  if numero == 20:
    ind2 = j
  j+=1

soma = array1[ind1] + array2[ind2]
print('\n',soma)

Vetor1 =  [10 20 30 40] 

Vetor2 =  [100  30   5   1  40 100  20 130 155 170] 

Primeiro elemento vetor1: 10
Primeiro elemento vetor2: 100
Terceiro elemento vetor1: 30
Terceiro elemento vetor2: 5
Último elemento vetor1: 40
Último elemento vetor2: 170

Vetor1 invertido = [40 30 20 10]
Vetor2 invertido = [170 155 130  20 100  40   1   5  30 100]

 40


# Exercício 25

Acesse os números 9 e 90 do array abaixo.

array = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])



In [ ]:
matrix = np.array([
    [-1,33,44,9,1],
    [11,1,0,90,44]
])

print(matrix[0][3])
print(matrix[1][3])

9
90


# Exercício 26

Acesse os números 5, 9, 3 e 21 do array abaixo.

ar = np.array([
    [[1, 1, 5, 1],
     [1, 1, 1, 9]],
    [[1, 3, 1, 1],
     [1, 1, 21, 1]]
              ])

In [ ]:
matrix = np.array([
    [1,1,5,1],
    [1,1,1,9],
    [1,3,1,1],
    [1,1,21,1]
])

print(matrix[0][2])
print(matrix[1][3])
print(matrix[2][1])
print(matrix[3][2])

5
9
3
21


# Exercício 27

Com base no array abaixo obtenha o slice do índice 2 até o índice 6.

ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

print(array[2:7])

[3 4 5 6 7]
